### ISSUE TITLE
Confusion about dataset and experiment

### ISSUE THREAD

**Issue by mochong** [Lee-zix/RE-GCN#4]
Hello, I have some confusions about GEDLT dataset. The training set of GDELT is 1734399 in your paper, but it's down to about a million in the code. May I ask why the data set in the experiment is different from the data set in the paper?

The sceond is when I use CyGNet to experiment on the ICEWS14 dataset in your code, I get better results than your paper.
The result I have gotten is below:

python test.py --dataset ICEWS14s                                                           
Namespace(alpha=0.5, batch_size=1024, counts=4, dataset='ICEWS14s', entity='object', gpu=0, hidden_dim=200, lr=0.001, n_epochs=30, raw=False, regularization=0.01, time_stamp=1, valid_epoch=5)
num_times 366
start object testing:
Using best epoch: 7
test object-- Epoch 0007 | Best MRR 0.5029 | Hits@1 0.4366 | Hits@3 0.5419 | Hits@10 0.6185
start subject testing:
Using best epoch: 8
test subject-- Epoch 0008 | Best MRR 0.4795 | Hits@1 0.4084 | Hits@3 0.5197 | Hits@10 0.6051

final test --| Best MRR 0.4912 | Hits@1 0.4225 | Hits@3 0.5308 | Hits@10 0.6118

**Comment by Lee-zix** [comment]
We have updated the complete data files. For the results of CyGNet, note that all the results in the paper are under the raw setting and the reasons are stated in Section 5.1.2.

**Comment by JinchuanZ** [comment]
I have got the same questions(confusions) about the experiments of those baselines, that RE-NET and CyGNet results are different from the original paper.

**Comment by Lee-zix** [comment]
That is because RE-NET and CyGNet use filter metrics but not raw metrics. The filter metrics are not suitable for the extrapolation setting.
