### ISSUE TITLE
confusion about dataset

### ISSUE THREAD

**Issue by lbq8942** [Lee-zix/RE-GCN#7]
![image](https://user-images.githubusercontent.com/64315774/144829979-ad874a91-aa5c-451d-aa50-a95b0e3428e9.png)

can someone tell me what's "24" and "0" mean?What i know is all lines with 24 are events happens on 2018-01-02,but i don't know why 2018-01-02 is encoded as 24 and what does the last column represent?

**Comment by Lee-zix** [comment]
The value denotes the time granularity is 24 hours. Thus, 2018-01-01, 2018-01-02,..., are denoted as 0, 24, 48.......    The last column represents the end time of the event. In ICEWS datasets, it is a padding value that has no meaning.

**Comment by lbq8942** [comment]
I see, thank you so much.
