### ISSUE TITLE
confusion about parameter(skip_connect)

### ISSUE THREAD

**Issue by lbq8942** [Lee-zix/RE-GCN#8]
i found `skip_connect=True` never works in your code.
it is used in a layer as follows:
```
            for i, layer in enumerate(self.layers):
                layer(g, [], init_rel_emb[i])
```
and layer calls for the following code,and bool expression `len(prev_h) != 0 and self.skip_connect` is forever False.
```
    def forward(self, g, prev_h, emb_rel):
        self.rel_emb = emb_rel
        if len(prev_h) != 0 and self.skip_connect:
            skip_weight = F.sigmoid(torch.mm(prev_h, self.skip_connect_weight) + self.skip_connect_bias) 
```
so this parameter doesn't work,is there something wrong?

**Comment by Lee-zix** [comment]
Yes, the parameter is not used in the final version of the model because we already have the time-gate unit, which can be seen as the skip connect across timestamps.
