### ISSUE TITLE
Confusion about YAGO and WIKI

### ISSUE THREAD

**Issue by ld-maker** [Lee-zix/RE-GCN#9]
Thank you for sharing your code. I find that YAGO and WIKI data sets in the code do not have ent2word.py, so e-w-graph.txt cannot be generated. I hope you can answer my doubts

**Comment by Lee-zix** [comment]
Yes, We can not get the static graph by ent2word.py, which constructs the graph by the static information contained in the entity names.  for WIKI and YAGO. Thus we report the results without a static graph in the paper. 
To let RE-GCN utilize the static information, you can construct the static graph by your own codes for these two datasets (maybe linking the entities in WIKI to their wiki pages and get their attributes) and store them in the format of (h, r, t).

**Comment by ld-maker** [comment]
Thank you very much for your answer
